import { Geist, Geist_Mono, Bebas_Neue } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 🆕 FUENTE DEPORTIVA PARA EL NAVBAR
const bebasNeue = Bebas_Neue({
  weight: "400", // Bebas solo tiene un peso disponible
  subsets: ["latin"],
  variable: "--font-bebas",
});

export const metadata = {
  title: "Reservá5 - Reserva canchas de fútbol en segundos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bebasNeue.variable} antialiased`}
      >
        <SessionProvider>
          <Navbar />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
